### ISSUE TITLE
Feed mode no longer shears sheep.

### ISSUE THREAD

**Issue by LexiTehGallade** [flier268/AutoHarvestMod#15]
Unlike original mod, feed mode does not shear sheep when shears are held in hand. Broken? Missing?

Game version: 1.17.1 using latest 1.16 build I compiled after the successful 1.17 pull request.

Reproduce: Hold shears with feed mode enabled, nothing happens.

**Comment by flier268** [comment]
2c7167761aa446c5aa8565c92685c84c1c79b4b4
