### ISSUE TITLE
How to slowdown the speed?Such as one harvest per 0.5 second.

### ISSUE THREAD

**Issue by crosspedestrian** [flier268/AutoHarvestMod#9]
like the title.
The mod is useful and comfortable, but sometimes users are kicked by anti-cheat plug-in unit, because harvest too fastly.
thanks.

**Comment by flier268** [comment]
e041bc8ea44d171e2f051006c0af99bf2370a7c0

**Comment by flier268** [comment]
Try to upgrade to 1.1.0.
If you don't have issue, close it yourself plz.
